### PR TITLE
Add one in english and two in spanish!

### PR DESCRIPTION
**Pull request by oscargil**
I make my little contribution

### CODE REVIEW

**Review by xnt — CHANGES_REQUESTED** [review]
This is very, very cool. Thank you, @Gostilian !

May I suggest removing the reference to "code"? We're trying to keep this component as generic as possible, and I feel like referencing "code" gives the impression that whoever reads it is writing code.

If that's your intent though, perhaps you want to look into #3 ?

Thank you again!

**Comment by oscargil** [comment]
Done! @xnt

**Comment by oscargil** [comment]
> This is very, very cool. Thank you, @Gostilian !
> 
> May I suggest removing the reference to "code"? We're trying to keep this component as generic as possible, and I feel like referencing "code" gives the impression that whoever reads it is writing code.
> 
> If that's your intent though, perhaps you want to look into #3 ?
> 
> Thank you again!

Changes commited!

**Review by sau2019 — APPROVED** [review]

**Comment by xnt** [comment]
Thank you @Gostilian , and sorry for the delay!

**Pull request merged**
