### PR TITLE
21 new message added

### PR DESCRIPTION
**Pull request by nourhan-anber**

### CODE REVIEW

**Comment by nourhan-anber** [comment]
Resolves #7

**Comment by xnt** [comment]
Hi @nourhan-anber  ! I think I accidentally turned off PR notifications. I'll check this out early tomorrow. Thank you for your contributions (I see you actually submitted 2, *so* cool!!)!!

**Review by xnt — CHANGES_REQUESTED** [review]
I really like some of these messages, but I'd like us to see if it conflicts with #11 . Lets' try and merge afterwards.

**Comment by nourhan-anber** [comment]
@xnt  Please review

**Pull request closed without merging**
